/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-noun-physiotherapy-3521284': '&#xe94c;',
		'icon-noun-therapy-4281968': '&#xe900;',
		'icon-activity': '&#xe901;',
		'icon-alert-circle': '&#xe902;',
		'icon-alert-octagon': '&#xe903;',
		'icon-alert-triangle': '&#xe904;',
		'icon-arrow-down': '&#xe905;',
		'icon-arrow-down-left': '&#xe906;',
		'icon-arrow-down-right': '&#xe907;',
		'icon-arrow-left': '&#xe908;',
		'icon-arrow-left-circle': '&#xe909;',
		'icon-arrow-right': '&#xe90a;',
		'icon-arrow-right-circle': '&#xe90b;',
		'icon-arrow-up': '&#xe90c;',
		'icon-arrow-up-circle': '&#xe90d;',
		'icon-arrow-up-left': '&#xe90e;',
		'icon-arrow-up-right': '&#xe90f;',
		'icon-at-sign': '&#xe910;',
		'icon-bell': '&#xe911;',
		'icon-bell-off': '&#xe912;',
		'icon-calendar3': '&#xe94a;',
		'icon-check': '&#xe913;',
		'icon-chevron-down': '&#xe914;',
		'icon-chevron-left': '&#xe915;',
		'icon-chevron-right': '&#xe916;',
		'icon-chevron-up': '&#xe917;',
		'icon-circle': '&#xe918;',
		'icon-clipboard': '&#xe919;',
		'icon-credit-card1': '&#xe91a;',
		'icon-dollar-sign': '&#xe94b;',
		'icon-facebook1': '&#xe91b;',
		'icon-home1': '&#xe91c;',
		'icon-linkedin1': '&#xe91d;',
		'icon-list': '&#xe91e;',
		'icon-mail1': '&#xe91f;',
		'icon-map-pin': '&#xe920;',
		'icon-menu': '&#xe921;',
		'icon-message-circle': '&#xe922;',
		'icon-message-square': '&#xe923;',
		'icon-minus1': '&#xe924;',
		'icon-minus-circle': '&#xe925;',
		'icon-minus-square': '&#xe926;',
		'icon-monitor': '&#xe927;',
		'icon-more-horizontal': '&#xe928;',
		'icon-more-vertical': '&#xe929;',
		'icon-phone1': '&#xe92a;',
		'icon-phone-call': '&#xe92b;',
		'icon-plus1': '&#xe92c;',
		'icon-plus-circle': '&#xe92d;',
		'icon-plus-square': '&#xe92e;',
		'icon-settings': '&#xe92f;',
		'icon-shopping-cart': '&#xe930;',
		'icon-trash': '&#xe931;',
		'icon-trash-2': '&#xe932;',
		'icon-twitter1': '&#xe933;',
		'icon-user1': '&#xe934;',
		'icon-users1': '&#xe935;',
		'icon-x': '&#xe936;',
		'icon-x-circle': '&#xe937;',
		'icon-x-octagon': '&#xe938;',
		'icon-x-square': '&#xe939;',
		'icon-youtube1': '&#xe93a;',
		'icon-zoom-in1': '&#xe93b;',
		'icon-zoom-out1': '&#xe93c;',
		'icon-home-outline': '&#xe93d;',
		'icon-home4': '&#xe93e;',
		'icon-calendar': '&#xe946;',
		'icon-date': '&#xe946;',
		'icon-schedule': '&#xe946;',
		'icon-home': '&#xe93f;',
		'icon-home2': '&#xe940;',
		'icon-home3': '&#xe941;',
		'icon-play': '&#xe942;',
		'icon-cart': '&#xe943;',
		'icon-credit-card': '&#xe944;',
		'icon-phone': '&#xe945;',
		'icon-location': '&#xe947;',
		'icon-location2': '&#xe948;',
		'icon-calendar2': '&#xe953;',
		'icon-bubbles': '&#xe96c;',
		'icon-bubbles2': '&#xe96d;',
		'icon-bubble2': '&#xe96e;',
		'icon-bubbles3': '&#xe96f;',
		'icon-bubbles4': '&#xe970;',
		'icon-user': '&#xe971;',
		'icon-users': '&#xe972;',
		'icon-spinner6': '&#xe97f;',
		'icon-spinner7': '&#xe980;',
		'icon-zoom-in': '&#xe987;',
		'icon-zoom-out': '&#xe988;',
		'icon-aid-kit': '&#xe998;',
		'icon-accessibility': '&#xe9b2;',
		'icon-warning': '&#xea07;',
		'icon-notification': '&#xea08;',
		'icon-question': '&#xea09;',
		'icon-plus': '&#xea0a;',
		'icon-minus': '&#xea0b;',
		'icon-info': '&#xea0c;',
		'icon-cancel-circle': '&#xea0d;',
		'icon-blocked': '&#xea0e;',
		'icon-cross': '&#xea0f;',
		'icon-checkmark': '&#xea10;',
		'icon-checkmark2': '&#xea11;',
		'icon-circle-up': '&#xea41;',
		'icon-circle-right': '&#xea42;',
		'icon-circle-down': '&#xea43;',
		'icon-circle-left': '&#xea44;',
		'icon-ctrl': '&#xea50;',
		'icon-table': '&#xea70;',
		'icon-table2': '&#xea71;',
		'icon-mail': '&#xea83;',
		'icon-mail2': '&#xea84;',
		'icon-mail4': '&#xea86;',
		'icon-google': '&#xea88;',
		'icon-google2': '&#xea89;',
		'icon-google3': '&#xea8a;',
		'icon-google-plus': '&#xea8b;',
		'icon-google-plus2': '&#xea8c;',
		'icon-google-plus3': '&#xea8d;',
		'icon-google-drive': '&#xea8f;',
		'icon-facebook': '&#xea90;',
		'icon-facebook2': '&#xea91;',
		'icon-instagram': '&#xea92;',
		'icon-whatsapp': '&#xea93;',
		'icon-twitter': '&#xea96;',
		'icon-youtube': '&#xea9d;',
		'icon-youtube2': '&#xea9e;',
		'icon-tumblr': '&#xeab9;',
		'icon-tumblr2': '&#xeaba;',
		'icon-linkedin': '&#xeac9;',
		'icon-linkedin2': '&#xeaca;',
		'icon-pinterest': '&#xead1;',
		'icon-pinterest2': '&#xead2;',
		'icon-calendar1': '&#xe949;',
		'icon-date1': '&#xe949;',
		'icon-schedule1': '&#xe949;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
